# Generated by Django 5.2.7 on 2025-11-05 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('duracion', models.CharField(max_length=50)),
                ('ponente', models.CharField(max_length=100)),
                ('tipo_taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talleres', to='talleres.tipotaller')),
            ],
        ),
    ]
